### ISSUE TITLE
object as tag

### ISSUE THREAD

**Issue by alfredopacino** [zellerda/Tokenize#103]
Hi, my ajax source responses is in the form:
```
[{
	"_id": "56b351e01680a9c815efbaa8",
	"name": "John",
	"age": 20,
	"__v": 0
}, {
	"_id": "56b352551680a9c815efbaa9",
	"name": "James",
	"age": 20,
	"__v": 0
}]
```

I would keep those infos. I'm searching for a method for getting the tags from tokenize in this form (in this case I selected from the dropdown "John" and I added a new tag  "Mary"):
```
[{
	"_id": "56b351e01680a9c815efbaa8",
	"name": "John",
	"age": 20,
	"__v": 0
}, {
"name":"Mary",
"value":"Mary"
}
```

the method 

> $('#tokenize').tokenize().toArray();

returns just an array of strings...

**Comment by zellerda** [comment]
Not possible with this version, maybe in version 2

**Comment by alfredopacino** [comment]
I've just replaced my tokenize 2.5 (from bower) with your 2.6 (form this repository), but
```
    console.log($('#tokenize').tokenize().toArray());
```
prints still an array of strings.

this is my init, maybe there is something wrong here
```
$('#tokenize').tokenize({
        datas: "/api/community/users",
        displayDropdownOnFocus:true,
        searchMinLength:0,
        searchParam:'q',
        valueField:'_id',
        textField:'name',
        onAddToken:function(v, t, e){
            if(v==t)
                $('#tokenize').tokenize().tokenRemove(v);

        }
    });
```

side question:
I set searchMinLength:0 and displayDropdownOnFocus:true:, I want to see the first results onFocus, but it doesn't works neither.
very thanks!

**Comment by zellerda** [comment]
displayDropdownOnFocus on focus doesn't work with ajax
https://github.com/zellerda/Tokenize/issues/62

**Comment by alfredopacino** [comment]
so there is no way to see the first results using ajax in tokenize?

**Comment by zellerda** [comment]
In the very begining of the plugin this behavior was implemented but retired next, I got some issues with that. I will probably thinking of it for Tokenize2.

If you really need to display the dropdown on click, just change the data option and fill the select with all your values, personally I don't use ajax because with the search it can be a lot of load on the server for a simple value.

**Comment by alfredopacino** [comment]
I really need this features, other tokenizer plugins have this, but I want to use tokenize.
There is an onFocus event? I can't see in docs

**Comment by zellerda** [comment]
No but you can catch the focus event of the input with jQuery

**Comment by alfredopacino** [comment]
```
    $('#tokenize').focus(function() {
        $('#tokenize').tokenize().tokenAdd('test','test1');

    });
```
it doesn't work, anyway I don't think it's a safe solution..
so I should switch on a dead tokenize plugin project like bootstrap tagsinput or tokenfield?  :(
