### ISSUE TITLE
tokenAdd() doesn't work if newElements:false

### ISSUE THREAD

**Issue by alfredopacino** [zellerda/Tokenize#104]
Hi, this is my case:
I don't want to allow the users to set new tags directly.
If he wants add a new tag there is a form with an input field who save a new record in the database (so after that he can find it in ajax dropdown).
But this code doesn't work if I set newElements:false
```
$('#postedBy_add_button').click(function(e){
            $.ajax({
                type: "POST",
                url: "/api/community/users",
                data: JSON.stringify({name:$('#postedBy_add_name').val()}),
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
            }).done(function( data ) {
                $('#tokenize').tokenize().tokenAdd(data.user._id,data.user.name);
            }).fail(function( e ) {
                console.log( e );
            });
        });
```

**Comment by zellerda** [comment]
Hi,
There is two solutions for your problem,

1. just add $('#tokenize').tokenize({ newElement: true }) before "tokenAdd" and $('#tokenize').tokenize({ newElement: false }) the line after

2. Add the item first in the select object and then use "tokenAdd"

**Comment by alfredopacino** [comment]
I solved in this way, I guess it's the same (without newElements:false )
```onAddToken:function(v, t, e){
            if(v==t)
                $('#tokenize').tokenize().tokenRemove(v);

        }
```
or there are side effects?

**Comment by zellerda** [comment]
In your case I think no
