### ISSUE TITLE
How to check the response of search is empty in ajax search

### ISSUE THREAD

**Issue by Anazvak** [zellerda/Tokenize#105]
I am unable to get the method for getting the response after ajax request .I am also unable to show loading image in searchbox.I have seen onAddtoken,onRemoveToken methods,but I need to know a function which can be used when user types a letter,so that I can show a loading image .Also how to check response

**Comment by zellerda** [comment]
Loading are not supported for this plugin.
This will be implemented with tokenize2 (new version), but I don't have any release date for the moment
