### ISSUE TITLE
Clear function

### ISSUE THREAD

**Issue by Kumar-Pintu** [zellerda/Tokenize#111]
I have a case for making selection using tokenizer for Country and after that City tokenizer  that is populated on the basis of selected country tokenizer. Now I have to reset/clear the City tokenizer when Country tokenizer is changed/reset. I am using following code:
**
#  $('#CountryAjax').tokenize({
    datas: "../.../filename",
    onRemoveToken:function(value, e){
    
     $('#cityAjax').tokenize().clear();

    }
#  });
**

I have also tried others options, but still no help :(. Any help will be much appreciated.

Thanks & Regards,
Pintu Kumar

**Comment by zellerda** [comment]
Try to use maxElements: 1

**Comment by Kumar-Pintu** [comment]
Hi Zellerda,

May be I did not able to convey my problem. In simple word, "I want to clear cityToken input box when any change happens in countryToken input box i.e removeToken"
Other Example:
1. User selecting US as countryToken input box
2. Chicago in cityToken input box
3. When user changes his countryToken input box, then I want to reintailize cityToken input box no previous selection.It should be empty.

P.S. thanks for response.

Thanks & Regards,
Pintu Kumar

**Comment by zellerda** [comment]
Ok I understand now what you want to do !
Your code below should work, are you sure that you use the last version of tokenize, if not try to use data('tokenize') instead of tokenize() to call the api
