### ISSUE TITLE
Ajax Issue

### ISSUE THREAD

**Issue by baselbj** [zellerda/Tokenize#112]
I am trying to use this script using Ajax and I find out that in ( search: function()) in this line:

$.each(data, function(key, val) will not work as the ajax response is an object and when I change the line to ($.each(data.result, function(key, val)) it works fine.

I am not a javascript expert and I don't know if this solution is fine but I think you have to make an php example to show us how Ajax works.

**Comment by zellerda** [comment]
I have created a wiki page for that https://github.com/zellerda/Tokenize/wiki/Ajax-search-with-PHP
