### ISSUE TITLE
Using a user defined variable

### ISSUE THREAD

**Issue by Aakash2** [zellerda/Tokenize#113]
Dear Sir,

Could you please tell me how can i set a string variable as 'No Results' for my json parsed data and show it in the dropdown in html? 
i have tried setting the value in the debounce function's else part as below:

this.debounce(function(){
                    $.ajax({
                        url: $this.options.datas,
                        data: $this.options.searchParam + "=" + $this.searchInput.val(),
                        dataType: $this.options.dataType,
                        success: function(data){
                            if(data){
                                $this.dropdownReset();
                                $.each(data, function(key, val){
                                    if(count <= $this.options.nbDropdownElements){
                                        var html;
                                        if(val[$this.options.htmlField]){
                                            html = val[$this.options.htmlField];
                                        }
                                        $this.dropdownAddItem(val[$this.options.valueField], val[$this.options.textField], html);
                                        count++;
                                    } else {
                                      //*************new code
					this.dropdownAddItem(nores, NoResults);					
					//$this.dropdownAddItem(val[noresults], val[NoResults] , html);
                                     //**************custom code end
                                        return true;
                                    }
                                });
                                if($('li', $this.dropdown).length){
                                    $('li:first', $this.dropdown).addClass('Hover');
                                    $this.dropdownShow();
                                    return true;
                                }
                            }
                            $this.dropdownHide();
                        },
                        error: function(xhr, text_status) {
                            $this.options.onAjaxError($this, xhr, text_status);
                        }
                    });

Thanks

**Comment by zellerda** [comment]
This functionality is not available
