### ISSUE TITLE
Double quotes are stripped from input

### ISSUE THREAD

**Issue by tomsoderlund** [zellerda/Tokenize#118]
`""` becomes just blank.

**Comment by zellerda** [comment]
Hi this issue cannot be corrected with this version, I will do it for the rebuit version
https://github.com/zellerda/Tokenize2

**Comment by tomsoderlund** [comment]
Cool, when do you plan to ship Tokenize2?
ᐧ

**Comment by zellerda** [comment]
I don't know right now I'm working on it but its depending of my personal time at work

**Comment by tomsoderlund** [comment]
Cool, we might have to do a patch before then. We love Tokenize v1
otherwise! Great work! We use it in www.weld.io
ᐧ
