### ISSUE TITLE
How to prefill with default values

### ISSUE THREAD

**Issue by adarsh10** [zellerda/Tokenize#126]
I am using this plugin. I have an array object. I want to add the token in the input by default. for not i am trying to add a javascript come:

$('#tokenize').tokenize().tokenAdd(value, text);

unfortunately from the javascript file, this didnt work but when using this code in console, it works perfectly.

Please help me!

**Comment by zellerda** [comment]
Try this:
```javascript
$(function(){
    ...
    $('#tokenize').tokenize().tokenAdd(value, text);
    ...
});
```

**Comment by adarsh10** [comment]
I am trying to do this in on ready() function.

**Comment by adarsh10** [comment]
sir, 
it will be really great if you can solve the above mentioned issue

**Comment by zellerda** [comment]
Ok I understand your problem, if you want add item in the select on load that not listed in the select options you have to set the option **newElements** at **true**.

**Comment by adarsh10** [comment]
Thank you sir! worked like a charm. There is one more issue. I have a list of localities in an array object. Total count of localities is 35. I am putting these localities in the drop down using this code in my javascript:

    localityList.forEach(function(locality) {
        var id = locality.localityId;
        var name = locality.localityName;

        //trying to put the locality value in the dropdown list using append function
        var option = $('<option value=' + id + '></option>').text(name);
        $('#userLocality').append(option);
     });

But instead of containing 35 localities, the maximum no. of elements getting inserted is only 10. Is there any restrictions in it. Please help!

**Comment by zellerda** [comment]
Please read the doc: https://www.zellerda.com/projects/jquery/tokenize
By default the dropdown show only 10 values but you can incrase this value with **nbDropdownElements**
