### ISSUE TITLE
Optionally restrict auto-complete to beginning of word

### ISSUE THREAD

**Issue by jmcnair-enox** [zellerda/Tokenize#127]
Currently, if I type **_a_**, auto-complete shows me items that start with **_a_**. However if I type **_ai_** I see items that contain **_ai_** anywhere in the text. 

It would be useful to optionally be able to configure auto-complete to only match the start of text.

**Comment by zellerda** [comment]
Take a look here:
https://github.com/zellerda/Tokenize2
