### ISSUE TITLE
Hi! How to disable it? I used .attr() and had no result.

### ISSUE THREAD

**Issue by anton-korovaykin** [zellerda/Tokenize#15]

**Comment by zellerda** [comment]
Not implemented now, that will be in the next version

**Comment by zellerda** [comment]
Hi, I have published a new release with your proposition, to disable the tokenize:
- If on load just use disabled attr to the select <select disabled="disabled"></select>
- If after load, use the api $('#select').data('tokenize').disable(); or $('#select').data('tokenize').enable();

Don't forget to update your css if you use an other than mine.
