### ISSUE TITLE
Ajax data feed, adding, removing tokens

### ISSUE THREAD

**Issue by Adiqq** [zellerda/Tokenize#16]
My javascript skills are quite poor, but I needed to add token programatically , so I added event listener to code:
$(document).on('setTokenizeItem', function (e, data) {
                $this.clear();
                $this.tokenAdd(data.Value, data.Text, data.Html);
            });

Next I called trigger and it works fine for my specific case:
$(document).trigger('setTokenizeItem', [{ Value: data.CityId, Text: data.City }]);

Would it be possible to add similar functionality to project, but with more reusable code and probably implemented in some better way?

**Comment by zellerda** [comment]
Hi you can use the api like this:
`$('#your_tokenize').data('tokenize').tokenAdd(data.CityId, data.City);`

**Comment by Adiqq** [comment]
Thanks, it would be nice to have such example on project documentation website.
I couldn't come up with .data('tokenize') part on my own.
