### ISSUE TITLE
This is not a issue - I add a new option

### ISSUE THREAD

**Issue by fabiogomes2012** [zellerda/Tokenize#18]
Hi,

I did the download your plugin and i added a new option "minLength" to "query" when using a ajax request and in the code i do insert the verification code:

if (this.searchInput.val().length > this.options.minLength) {
//make the ajax request
}

If you want to use this functionality you are welcome

**Comment by zellerda** [comment]
Hello thank for your message.
Initially, I have added this parameter, but I removed it because it will causes some issue in some cases. 
It is replaced by searchMaxLength parameter who add maxlength attribute to the search input.

**Comment by fabiogomes2012** [comment]
All right!
