### ISSUE TITLE
Pre-Selected Values

### ISSUE THREAD

**Issue by ulysnep** [zellerda/Tokenize#20]
Thank you for creating this awesome, easy to use script! I've tried adding several values that are pre-selected using selected="selected" but only one will show up. Is there a work around for this or a code change that I could make to have pre-selected values? Thank you again!

**Comment by zellerda** [comment]
Hello, 
It's an html but you just forget to set multiple attribute to your select.
`<select multiple="multiple"></select>`

**Comment by ulysnep** [comment]
You're awesome! Thank you for the quick response! This worked just as you said!
