### ISSUE TITLE
How to Dynamic newElements : false

### ISSUE THREAD

**Issue by gitams** [zellerda/Tokenize#21]
Hi zellerda,
thank for this great plugin.
I am Using three multi select drop downs in a form by tokenize, i  want one field can accept new elements adding , but the remain two shouldn't accept - newElements : false is needed dynamically.
Configuring in js file reverts all. can u pull me out from this .... Thank u in Advance..

**Comment by zellerda** [comment]
Hi can you send me your code so I can check out ? You can send it to github@zellerda.com...

**Comment by gitams** [comment]
Sent you the code of my form

**Comment by zellerda** [comment]
Sorry ! this is the wrong address (not used anymore) send it to me@zellerda.com

**Comment by gitams** [comment]
ok, Sent to the new email address... thank u.

**Comment by zellerda** [comment]
I'm not sure to understand your problem ! Just add 
```javascript
$('#work_status').tokenize({ newElements: false });
```

If you want to change this value after loading, try this but I'm not sure that will work ?
```javascript
$('#work_status').data('tokenize').options.newElements = false;
```

**Comment by gitams** [comment]
ok thank u,
$('#work_status').tokenize({ newElements: false }); is suits for me.
thank u...
