### ISSUE TITLE
Debouncing Server Requests

### ISSUE THREAD

**Issue by Phant0mass** [zellerda/Tokenize#22]
I have included Tokenize in my non-commercial web site. It's really a great tool and saved me much time in creating my own suggest / multi-select from scratch. One item which I included in my Tokenize implementation is a debounce mechanic, whereby an ajax server request is not sent for every 'keyup' event, which would cause an unnecessary load on the server. I would suggest implementing a similar mechanic in your code for server-based requests. Here is the segment of code where I included debounce in my implementation. However, in a more general implementation, it may make sense to only debounce if 'search' is using ajax rather than pulling from a select element.

            case KEYS.BACKSPACE:
                        if(this.searchInput.val()){
                            this.debounce(this.search, 300);
                        } else {
                            this.dropdownHide();
                        }
                        break;
                    default:
                        if(this.searchInput.val()){
                            this.debounce(this.search, 300);
                        }
                        break;
                }
            }

        },
		  
		  debounce: function(func, wait){
				var $this = this;
				var later = function(){
					clearTimeout(timeout);
					func.call($this);
				};
				if(timeout)
					clearTimeout(timeout);
				timeout = setTimeout(later, wait);
        },

**Comment by zellerda** [comment]
Hi Phant0mass, this is a good idea I will implement it for the next version, I will just modify it a little bit to use debounce function only if ajax is used...
