### ISSUE TITLE
support for japanes text 

### ISSUE THREAD

**Issue by parth1729** [zellerda/Tokenize#23]
It is observed that when japanese text is entered it is not matching and showing japanese text properly for tokenizer.

**Comment by zellerda** [comment]
Hi, I just tested your issue, I have no problem with the current version:
![jap_issue](https://cloud.githubusercontent.com/assets/140013/7315713/5ae7194a-ea70-11e4-80ec-e3e7c8ca66bc.jpg)

Are you sure that your page are correctly in UTF8 ?
```html
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
```
