### ISSUE TITLE
$(this) in callback function

### ISSUE THREAD

**Issue by RaghavendhraK** [zellerda/Tokenize#24]
Hi

In callback functions, $(this) should provide the current select element, so that if we have used more than one select element as tokenize, then I can easily distinguish which select element is changed.

Thanks,
Raghu

**Comment by zellerda** [comment]
Hi I don't understand your problem, do you have a example of what you need ?

**Comment by RaghavendhraK** [comment]
Hi,

```html
<select name="currency1" class="tokenize">
  <option>INR</option>
  <option>USD</option>
</select>
<select name="currency2" class="tokenize">
  <option>INR</option>
  <option>USD</option>
</select>
```
```javascript
$('.tokenize').tokenize({
  onAddToken: function(value){
    console.log ($(this).attr('name'));
  }
});
```

I have two dropdowns. I tokenize them. 
On the callback functions, I need to perform operation based on the changed select box.

But $(this) gives the token object, not the select box jquery DOM element.

I hope you get it now.

Thanks,
Raghu

**Comment by zellerda** [comment]
Ok great I will check that !

**Comment by dimensionsxpert** [comment]
Where is the Json.php file?

**Comment by zellerda** [comment]
There is no "json.php" in the package, its just an example to explain how its work.
Json field are detailed in the doc on the "JSON fields" section.

**Comment by dimensionsxpert** [comment]
But it is not working on my side?

**Comment by zellerda** [comment]
Please open a new issue with your problem, and put an example of your json in it

**Comment by dimensionsxpert** [comment]
ok

**Comment by RaghavendhraK** [comment]
Thank you. :+1:

**Comment by cozumel424** [comment]
Hi, is this possible or easy to add in? I have the same issue! I know I could attach tokenize to unique ids but that creates a lot of code, so classes are better, but in the callback functions there doesn't seem to be anyway to get the calling element, just the token.

**Comment by RaghavendhraK** [comment]
OK, I guess it is easy to provide the select drop down unique attribute like name, id, etc... with the token, which solves the above problem
