### ISSUE TITLE
How do i bind it with JSON data in ASP.Net Webservices

### ISSUE THREAD

**Issue by amitRanjan** [zellerda/Tokenize#26]
Could you please elaborate this below more in terms of ASP.NET/ SQL Server / Webservices asmx. I am using a ASP.NET web service for pulling out data.

**Comment by zellerda** [comment]
Sorry I can't I'm not an asp developer, but I can explain the json search issue.

You have to get the POST parameter "search" of the query an search in your database and get the result in JSON format.

For each item in result, field "value" for the value of the option and field "text" for the displayed value in the autcomplete.

Example:
```json
[
    {
        "value": 1,
        "text": "Serina Beck"
    },
    {
        "value": 2,
        "text": "Yetta Craft"
    },
    {
        "value": 3,
        "text": "Martina Larson"
    }
]
```

**Comment by amitRanjan** [comment]
So if I am correct then, this would work:
$(document).ready(function () {
    $.ajax({
        url:  "http://localhost/myservices/Service1.asmx/ManagePointBasedRewards",
        data: { flag: 6 }, //parameter to webservice
        dataType: "jsonp",
        type: "POST",
        async: true,
        success: function (data) {
          $('#tokenize').tokenize({ datas: data}); //data = webservice output in array of objects
        },
        error: function () {
           alert( "No data found against this offer.");
        }
    });
});

**Comment by zellerda** [comment]
No use it just like this:
```javascript
$('#tokenize').tokenize({ datas: 'http://localhost/myservices/Service1.asmx/ManagePointBasedRewards?flag=6' });
```

**Comment by amitRanjan** [comment]
No success. Below Service is returning data in this format
SVC: http://localhost:50508/ViungoWebService.asmx/GetAllActivePointBasedRewards?flag=6

DATA: ({"d":"[{\"value\":1,\"text\":\"50 points gives you Burger with Coke\"},{\"value\":2,\"text\":\"50 points gives you zvzxv\"},{\"value\":3,\"text\":\"50 points gives you zczxc\"},{\"value\":4,\"text\":\"100 points gives you Chocobar\"}]"});

I am using this script only
$(document).ready(function () {
    $('#tokenize').tokenize({ datas: globalURL + 'GetAllActivePointBasedRewards?flag=6' });
});

HTML
 <select id="tokenize" multiple="multiple" class="tokenize-sample"></select>

**Comment by zellerda** [comment]
You have an issue on the begining of your json data, just remove "d":

**Comment by amitRanjan** [comment]
is the value,text properties of JSOn case sensitive

**Comment by zellerda** [comment]
The tokenize plugin doesn't make search in ajax mode, the search query is transmited to the server with "search" parameter, if you want to filter, you have to do it on the server.

**Comment by amitRanjan** [comment]
that means, if i had to filter name say 'Jon Bosco' , then i will have to fire a webmethod that accepts name  as a parameter and that name is queried against database. if matching criteria satisfies then we will have the result otherwise not.. is that ???

**Comment by amitRanjan** [comment]
What I got was that, on page load, it fires the url and saves data at client in key value pair and then does a search and select.

**Comment by zellerda** [comment]
Use "search" as parameter or define the parameter name like this:
```javascript
$(document).ready(function () {
    $('#tokenize').tokenize({ 
        datas: globalURL + 'GetAllActivePointBasedRewards?flag=6',
        searchParam: 'name'
     });
});
```

If you have all your data loaded on page, that will be more easy to add the options in your select and use tokenize with "datas" parameter has "select"

```html
<select id="tokenize" multiple="multiple" class="tokenize-sample">
   <option value="1">50 points gives you Burger with Coke</option>
  ...
</select>
<script>
$(document).ready(function(){
    $('#tokenize').tokenize();
});
</script>
```
