### ISSUE TITLE
custom json key value

### ISSUE THREAD

**Issue by vallurisundeep** [zellerda/Tokenize#28]
Hi,

I would like to use custom key values instead of 'value' and 'text' in JSON. any alternative for that?

**Comment by zellerda** [comment]
Hi, as explain in the documentation (http://zellerda.com/projects/jquery/tokenize) you can use "valueField" and "textField" to customize json.

```javascript
$('#tokenize').tokenize({
    datas: "json.php",
    valueField: "myvalue",
    textField: "mytext"
});
```

**Comment by vallurisundeep** [comment]
HI Zellerda,

Thanks for your quick reply. I have one more doubt please help me. My client requirement is on select of any value I need to display both option value and text in 'TokensContainer' like 'value - text'. and need to show title on hover of selected value.

**Comment by zellerda** [comment]
You can use "htmlField"
