### ISSUE TITLE
Callbacks for tokens that are not from the json

### ISSUE THREAD

**Issue by dansa** [zellerda/Tokenize#29]
Hi, I really like this plugin! Works very well :smile: 
I wonder if there would be a possibility to check which tokens are added from the json results and which ones are "custom" (written by the user)
My users should only be able to submit the tokens that are valid according to my json file, which I will check for in my php when they are submitting the form.
But it would be nice to show the users which tokens will not be accepted (changing the class or something) 
So I think a callback or method to check that would be cool!

**Comment by zellerda** [comment]
Hi, you can set "newElements" to "false" in options

**Comment by dansa** [comment]
Sorry! I think I was a bit too tired, was looking through the list for a long time to figure out how I could do this but didn't see the newElements option!

Thank you for quick help anyway!

**Comment by zellerda** [comment]
No problem ^^
