### ISSUE TITLE
Load and add predefined tokens on init/pageload

### ISSUE THREAD

**Issue by dansa** [zellerda/Tokenize#30]
Hi again. I noticed today that I am kind of lacking a way to add tokens myself when the page is initialized.
I am using Tokenize for a form, and when saving the form the tokenize "results" (and a bunch of other things) is sent to my server for storage, so that the user can later edit the form, and all the old data gets loaded.
This is a bit hard to do with tokenize it seems to me?
Basically on pageload I would like to do something like this:

```javascript
$('select#tokenize').tokenize();
var field = $('input[name=champs]'),
    fieldvalues = field.val().split(' ') || [];
if (!$.isEmptyObject(fieldvalues)) {
    $.each(fieldvalues, function (i, val) {
        //search json for val etc
});
  //update tokenize field with results and "select" them (add them to the tokenize input field)
}
```

If there is a way to achieve this I can't figure out how, otherwise would this be a feature that you could possibly look into adding?

**Comment by zellerda** [comment]
Hi, I'm not sure that I understand your problem, if you want just add tokens after the page load, you can use the api.

```javascript
$('select#tokenize').data('tokenize').tokenAdd(value, label);
```

P.S. I see that your input name is in french. French is my native language.

**Comment by dansa** [comment]
My input name is actually swedish :)
I want to add a number of values (that are grabbed from the server) to the tokenize field when the page is loaded

I tried to do something like this:
```javascript
if (!$.isEmptyObject(fieldvalues)) {
    $.each(fieldvalues, function (k, v) {
        $.ajax({
            url: ajaxurl,
            data: 'search=' + v,
            dataType: 'json',
            success: function (results) {
                $.each(results, function (i, val) {
                    console.log(val.clean, val.champion);
                    $('select#tokenize').data('tokenize').tokenAdd(val.clean, val.champion);
                });
            },
        });
    });
}
```

But it did not seem to add any tokens, am I misunderstanding something?
The correct data is output with the console.log but the tokenAdd function seemed to do nothing

**Comment by zellerda** [comment]
Your usage is correct I just tested the tokenAdd function. The only reason that it will not work it if tokenize have "newElements" = false and the "val.clean" value is not in the select element.

**Comment by dansa** [comment]
I see. 
Then it's because the newElements = false option is set.
It seems changing the code to this works as a solution for that problem
```javascript
if (!$.isEmptyObject(fieldvalues)) {
    $('select#tokenize').data('tokenize').options.newElements = true;
    $.each(fieldvalues, function (k, v) {
        $.ajax({
            url: ajaxurl,
            data: "search=" + v,
            dataType: 'json',
            success: function (results) {
                $.each(results, function (i, val) {
                    $('select#tokenize').data('tokenize').tokenAdd(val.clean, val.champion);
                });
            }
        });
    }).promise().done( function() {$('select#tokenize').data('tokenize').options.newElements = false; });
}
```

**Comment by zellerda** [comment]
I think that will work, the second solution is to add the all options element in the select (with php) whitout "selected" attribute, before tokenize load, so you don't have to change newElements option.

**Comment by dansa** [comment]
I think just setting the option to false after the "preload" is done is the easiest method instead of writing a new php function just for adding all the options, and I don't think it will cause any problems.
I also modified the code above a bit because I realized promise() would not work like that :P
