### ISSUE TITLE
Agregar eventos

### ISSUE THREAD

**Issue by csportisc** [zellerda/Tokenize#31]
A veces es muy necesario intervenir en la forma en la que se generan los elementos de la lista de búsqueda, por lo que sería muy oportuno agregar eventos en ciertos momentos, como al agregar un ítem a la lista "dropdown" ya que la información que obtengo por ajax se necesita procesar antes de ser mostrada, por ejemplo concatenar dos campos o más:

------------------------------------------------------- ORIGINAL
389         var html = undefined;
390         if(val[$this.options.htmlField]){
391           html = val[$this.options.htmlField];
392         }
393         $this.dropdownAddItem(val[$this.options.valueField], val[$this.options.textField], html);
394         count++;
....
------------------------------------------------------- PROPUESTA
389         $this.options.onDropdownAddItem($this, val);
390         count++;
....
557        $.fn.tokenize.defaults = {
        ...........
        onAddToken: function(value, text, e){},
        onRemoveToken: function(value, e){},
        onClear: function(e){},
        onDropdownAddItem: function($this, val){
           var html = undefined;
           if(val[$this.options.htmlField]){
               html = val[$this.options.htmlField];
           }
           $this.dropdownAddItem(val[$this.options.valueField], val[$this.options.textField], html);
        }
    };

**Comment by zellerda** [comment]
Hi can you try the last commit, I have added the onDropdownAddItem event.

```javascript
onDropdownAddItem: function(value, text, html, e){}
```
https://raw.githubusercontent.com/zellerda/Tokenize/master/jquery.tokenize.js

*For the next issues, please write your issue in english or french, so I can easly understand your question or problem ^^ Thanks !*
