### ISSUE TITLE
set newElements to "false" problem

### ISSUE THREAD

**Issue by vinothrao84** [zellerda/Tokenize#32]
Hi,

When i set newElements to "false", my existing data is gone missing upon ajax complete.
If i set to "true", then my existing data shows fine.

Do you encounter this problem?

Thx.

**Comment by zellerda** [comment]
Hi I just checked it works on my example. 
You have to use TAB key or click on the dropdown item to add it.

**Comment by vinothrao84** [comment]
Hi zellerda,

Do you have any live example? As in example like existing data pre-loaded with newElements to "false"?

Thx.

**Comment by zellerda** [comment]
Here is my version 
http://zellerda.com/files/projects/tokenize/TokenizeSample.zip
