### ISSUE TITLE
Expected Behavior

### ISSUE THREAD

**Issue by roglor1** [zellerda/Tokenize#33]
I've implemented this using the latest package.  Is the expected behavior that when you type say "B", you would get all the results that start with "B"?  That is not happening, I get some stray results that don't start with "B".  It's only when I type three or more letters that I get the items that match the beginning letters I types.  I was expecting that when I "Sy", I would only get those items that start with "Sy".

**Comment by zellerda** [comment]
Hi, it's normal, actually the plugin search like this " * your search * ".
If you want to search from the begining of a string, you have to switch to AJAX usage and make the search yourself.

To do this put your PHP or ASP like in "datas" option. In the script get "search" parameter from request, do the search in your values and retrieve the value in json format.

Example of JSON:
```JSON
[
    {
        "value": 1,
        "text": "Serina Beck"
    },
    {
        "value": 2,
        "text": "Yetta Craft"
    }
]
```
