### ISSUE TITLE
Get all selected tokens

### ISSUE THREAD

**Issue by alokpant** [zellerda/Tokenize#34]
Hi

Is there a way to get all selected tokens? I looked in documentation but unable to get all tokens when new one is added.

```
      onAddToken: function (value, text, e) {
         console.log(value);
      }

```

only gives value or text. But is there a way to get other values as well?

Thank you.

**Comment by zellerda** [comment]
```javascript
onAddToken: function (value, text, e) {
    $('option:selected', this.select).each(function(){
        console.log($(this).attr('value'), $(this).html());
    });
}
```

**Comment by alokpant** [comment]
Wooaah... thank you very much... that was super quick... you are awesome.
