### ISSUE TITLE
Typing a " gives a JS error

### ISSUE THREAD

**Issue by tbalthazar** [zellerda/Tokenize#36]
Thanks for your great plugin!
I noticed a problem :
If you type `foo"` the `tab`, the word is not tokenized and there is this JS error in the console : `Error: Syntax error, unrecognized expression: option[value="foo""]`.

**Comment by zellerda** [comment]
Hi,
Can you give me your tokenize options {} ?

**Comment by tbalthazar** [comment]
I noticed the problem on the first example "Placeholder option" on your website :
http://zellerda.com/projects/jquery/tokenize

**Comment by zellerda** [comment]
I don't have any errors ! 
Which bowser do you use ?
Which operating system ?
Did you try to empty your browser cache ?

**Comment by tbalthazar** [comment]
I can reproduce it on Debian with Chrome 43.0.2357.81, on Mac OS 10.10.3 with Safari 8.0.6, Firefox 38.0.1 and Chrome 43.0.2357.65. I tried to empty the cache.
Here is a video of the problem (I type `foo"<tab>` in the video) :
https://www.dropbox.com/s/n4q8e92vibez4dy/tokenize.mov?dl=0

**Comment by zellerda** [comment]
Ha ok I understand !
Added to fix...

**Comment by tbalthazar** [comment]
Cool, thanks! ;)
