### ISSUE TITLE
css style function

### ISSUE THREAD

**Issue by lisabonde** [zellerda/Tokenize#37]
It would be very nice to have a bootstrap 3 css with glow on input and rounded corners on Tokenize div
I tried to style it, but can't get div.Tokenize:focus css to work.
Beside that, your component is the best...thank's for your work...

**Comment by zellerda** [comment]
I will add a class "Focus" when tokenize has the focus

**Comment by lisabonde** [comment]
Very kind of you..thank oyu soooooo much
