### ISSUE TITLE
Remove the current non-validated entry on quit

### ISSUE THREAD

**Issue by coudrak** [zellerda/Tokenize#38]
Hello, I like Tokenize because it's smaller than Select2, but there is one thing I really need, and I don't find. If the user writes  and selects "Switzerland", then "France", then writes "Blablabla" and quits the element without pressing "Esc", for example clicking on the next input or anywhere in the page, there is still "Blablabla" written in the box. I think it should be deleted because this entry has not been selected and doesn't exist in the list. What can I change in the code for that? Thanks! (I would love too if it would possible to select an existing entry not only with "Enter" but with "Space" too...)

**Comment by zellerda** [comment]
Hi currently it's not possible, I will check that when I will implement issue #37.
For the space key, i will not implement it, but if you need it you can do this modifications:

Line 24:
```javascript
var KEYS = {
    BACKSPACE: 8,
    TAB: 9,
    ENTER: 13,
    ESCAPE: 27,
    ARROW_UP: 38,
    ARROW_DOWN: 40,
    COMMA: 188,
    SPACE: 32
};
```
Line 320:
```javascript
case KEYS.TAB:
case KEYS.ENTER:
case KEYS.SPACE:
```

Line 364
```javascript
case KEYS.TAB:
case KEYS.ENTER:
case KEYS.ESCAPE:
case KEYS.ARROW_UP:
case KEYS.ARROW_DOWN:
case KEYS.SPACE:
```

**Comment by coudrak** [comment]
Thanks!

**Comment by coudrak** [comment]
Finally I found a easy solution, if I add this:
[code]
            this.searchInput.on('blur', function(e){
				$this.resetSearchInput();
            });	
[/code]
