### ISSUE TITLE
Manipulate Selected items using JS

### ISSUE THREAD

**Issue by dondude** [zellerda/Tokenize#41]
Hi,
sorry, me again, but i have another question:

how can i manipulate the selected attribute of the single options in such a tokenized-select. 
For example a reset:

function deselectAll(){	
var ob = document.getElementById("tokenize");
for (var i=0; i<ob.options.length; i++){
     	if (ob.options[i].selected){
			ob.options[i].selected = false;
		}
	}
}

This fct does not work. 
Is it possible and how?

Thx
dd

**Comment by zellerda** [comment]
Use clear() method with API
$('.tokenize').data('tokenize').clear();
