### ISSUE TITLE
Comma key and non-english layouts

### ISSUE THREAD

**Issue by Pathologic** [zellerda/Tokenize#43]
It's impossible to enter russian letter "б", because it uses the same key as comma. https://github.com/Pathologic/Selector/commit/41f70ce5478709b60abdd7b843f42c99c1c51ff7 - I've fixed it, but maybe there's more suitable way to fix? My JS is poor :cat:

**Comment by zellerda** [comment]
Hello I have make a change for your issue, could you please try it and give me a feedback, because I cannot test it, thanks in advance...

**Comment by Pathologic** [comment]
Now it works, thank you.
