### ISSUE TITLE
Disable the Token values

### ISSUE THREAD

**Issue by RaghavendhraK** [zellerda/Tokenize#44]
Hi,

I have two dropdowns, which are mutually exclusive. i.e., a value selected in one, should not be allowed to select in the other.
So, I need to grey out and not allowed to select the particular values in the list. I checked in the documentation, but no avail.

Thanks,
Raghu

**Comment by zellerda** [comment]
With last update, use onAddToken or onRemoveToken to change the disabled attribute in the second select

**Comment by RaghavendhraK** [comment]
Hi,
Is it possible to grey out, instead of removing it, as the select dropdown behaves?
Thanks,
Raghu

**Comment by zellerda** [comment]
Sorry not possible without modifications that will update previous version implementation in user projects
