### ISSUE TITLE
A function to resync the UI according to selected state of individual options

### ISSUE THREAD

**Issue by gabrielzerbib** [zellerda/Tokenize#52]
Since you don't accept pull-request, can you please consider this addition: 4f7a5626fb04100ab38affd9c521b633be369f3b

Explanations in the commit, and in this issue's subject.
Thanks.

**Comment by zellerda** [comment]
Ok good idea I will add it in the next release

**Comment by gabrielzerbib** [comment]
Great, thanks!

**Comment by gabrielzerbib** [comment]
Ton commit 8108c0996632e2f8ea0cbbcc6a820e8762890bd4 ne marche pas. Essaie mon fichier de test, sur mon repo.
L'appel à 
````
this.clear();
```` 
en ligne 620, efface tous les choix, et la ligne suivante 
````
$("option:selected", this.select).each(...)
````
n'y change rien car c'est trop tard, les choix sont effacés.
Je pense qu'ouvrir les pull-request et intégrer les commit des autres, en les adaptant si nécessaire, est constructif et généralement apprécié sur GitHub ! :)

**Comment by zellerda** [comment]
Oups petit erreur de ma part c'est corrigé

**Comment by gabrielzerbib** [comment]
Pas mal. Merci.
Je préfère les noms de variables explicites, et les commentaires dans le code pour expliquer les passages pas intutifs, donc... je vais continuer de pointer sur mon repo pour mes projets, pour l'instant ! :)
Merci en tout cas pour cette belle base de travail.
