### ISSUE TITLE
Firefox: the form submission does not post selected options

### ISSUE THREAD

**Issue by gabrielzerbib** [zellerda/Tokenize#53]
(on Linux at least).
Options are selected using attr("selected", "selected) in tokenAdd, but on some browsers what gets really submitted are the options whose native DOM property selected = true.
I will try to propose a patch in my branch.

**Comment by gabrielzerbib** [comment]
Please check 1494b5b6048cd20351582b1a9adf81498fe9a067

**Comment by zellerda** [comment]
Hi thanks for your correction but it not work for me. The option element is remplaced by "true" value

![2015-07-20_07-10-16](https://cloud.githubusercontent.com/assets/140013/8770272/9213d278-2eae-11e5-90db-e7fcd65ee065.jpg)

**Comment by gabrielzerbib** [comment]
Hmm let me check. It worked for me in Cr and Ff. I will provide my test files later today.
Thanks

**Comment by gabrielzerbib** [comment]
Please check my test file here: https://github.com/gabrielzerbib/Tokenize/tree/master/test
I think it works.

**Comment by zellerda** [comment]
I have do a little change for this issue, I have tested it on FF linux it's work perfectly.
P.S. your last message don't refere to this issue...

**Comment by gabrielzerbib** [comment]
I think it was simply because the programmatic selection of an option must be made with .prop("selected", true) instead of attr( ).

**Comment by zellerda** [comment]
According jQuery forum prop() doesn't work with selected attribute, I don't now why ! jQuery problem I think !
