### ISSUE TITLE
Inconsistent pulls from the sorted items

### ISSUE THREAD

**Issue by stangsdado** [zellerda/Tokenize#54]
Hey there,

Wonderful multi-select. Interface works perfectly, however, after I re-sort items and attempt to pull the values, I get inconsistent sorting order. This is my code for pulling and adding to an array:

		var rollUps = [];
		var rawRollUps = $('#rollUpSelect').val();
		for (var key in rawRollUps)
		{
			rollUps.push(rawRollUps[key]);
		}

**Comment by stangsdado** [comment]
Follow up:

I think I've narrowed it down to the following:

Adding a once-removed option doesn't re-add it to the array of selected objects.

**Comment by zellerda** [comment]
I don't understand your issue, if you need an array just do
```javascript
$('#tokenize').val();
```

**Comment by stangsdado** [comment]
Both of those work. The problem I'm having is when I unselect one value and select it again, it does not appear in the array. For example:

Selectable values: 1, 2, 3, 4, 5
Selected values: 1, 2, 3

If I unselect 3, selected values becomes 1, 2.
If I select 3 again, selected values are still 1, 2.

**Comment by stangsdado** [comment]
See screenshot. I selected 3 values, spit out the array to the console. I unselected 1 value, spit out the array to the console. I re-selected the same value I unselected and spit out the array and it's not back. 

![screenshot](https://cloud.githubusercontent.com/assets/7524983/8826167/890794d0-3052-11e5-992e-99b1cd6c27d8.png)

**Comment by zellerda** [comment]
OK I think a see the problem I will check on that

**Comment by zellerda** [comment]
I have do some fix with the last commit, can you try on your code ?

**Comment by stangsdado** [comment]
Absolutely!

**Comment by stangsdado** [comment]
Same issue :/

**Comment by stangsdado** [comment]
I noticed now that when you unselect an item, it's not put back in in the same place. It's put back in on top of the list.

**Comment by zellerda** [comment]
The behavior with the selected item is normal, I need so to add a sorting when displaying dropdown.
BTW can you send me your code, so I can reproduce more easly your problem ?

**Comment by stangsdado** [comment]
Here is the code for declaring:

		<select id="rollUpSelect" multiple="multiple" class="tokenize-sample">
		    <option value="{FUNNEL}">Funnel</option>
		    <option value="{TRAFFIC_SOURCE}">Traffic Source</option>
		    <option value="{CAMPAIGN}">Campaign</option>
		    <option value="{OFFER}">Offer</option>
		    <option value="{LANDER}">Lander</option>
		    <option value="{GEO}">Country</option>
		    <option value="{DEVICE_TYPE}">Device Type</option>
		    <option value="{OS}">Operating System</option>
		    <option value="{HOUR}">Hour</option>
		    <option value="{DAY}">Day</option>
		</select>
		<script type="text/javascript"> $('#rollUpSelect').tokenize({displayDropdownOnFocus:true,sortable:true,maxElements:5,newElements:false});
		</script>

Here's the code for getting the value:

               var rollUps = $('#rollUpSelect').data('tokenize').toArray();
               console.log(rollUps);

**Comment by zellerda** [comment]
Ok I have reproduce the problem (it's only with Firefox) I will try to fix it !

**Comment by zellerda** [comment]
Can you try with the last commit ?

**Comment by stangsdado** [comment]
Worked like a charm! Thanks!!!
