### ISSUE TITLE
Option to Add tokens into another div tag and change suggestion list dynamically

### ISSUE THREAD

**Issue by nidhishah12** [zellerda/Tokenize#55]
Can you provide option to add tags into another div below the input field.

Also is it possible to change the suggestion list depending on the select option parameter as shown in the image? If yes, then please let me know. I am stuck here.

![image](https://cloud.githubusercontent.com/assets/13622409/9035234/b6663882-39f3-11e5-9c24-3929d3c5694f.png)

Thanks in advance!

**Comment by p-kumarg** [comment]
Can you please provide us code sample for the same functionality.


Thanks

**Comment by zellerda** [comment]
You have to create yourself the two dropdown and use tokenize api to add tokens in tokenize when user select an item in the second dropdown
```javascript
$('#my_tokenize').data('tokenize').tokenAdd('value', 'text');
```
