### ISSUE TITLE
Select All Option

### ISSUE THREAD

**Issue by masadi** [zellerda/Tokenize#56]
How to add select all button in one click?

**Comment by zellerda** [comment]
I don't understand what do you want to do, can you be a little more explicit please ?

**Comment by masadi** [comment]
like this
http://stackoverflow.com/questions/9924666/jquery-select-all-options-of-multi-select-select-box-on-click

**Comment by zellerda** [comment]
Ok, you can use the api
```javascript
$('#tokenize options').each(function(){
     $('#tokenize').data('tokenize').tokenAdd($(this).val(), $(this).html());
});
```

**Comment by masadi** [comment]
Failed. Here my code:

<script>
$('#tokenize').tokenize({
	displayDropdownOnFocus:true
});
$('#select_all').click(function() {
	$('#tokenize options').each(function(){
     $('#tokenize').data('tokenize').tokenAdd($(this).val(), $(this).html());
});

});
</script>

**Comment by zellerda** [comment]
Sorry its option not options

**Comment by masadi** [comment]
Yes!!! Success...
Thanks dear... :)
