### ISSUE TITLE
Remove item and add the same removed item

### ISSUE THREAD

**Issue by kevas** [zellerda/Tokenize#59]
If you display selectbox with selected items:
For example:

```html
<select multiple="multiple" class="multiselectbox" name="categories">
	<option value="3" selected="selected">cat1</option>
    <option value="6" selected="selected">cat5</option>
	<option value="5" selected="selected">cat2</option>
</select>
```

Then you do the following actions:
- delete item (for example item "cat2")
- you come back the same item that was removed ("cat2")

In the form, click on submit button and get this output:

```
'categories' => 
  array (size=2)
    0 => string '3' 
    1 => string '6'
```
    
Yes, in output is not item "cat2".

SOLUTION:

Change line 516

from:
```javascript
$('option[value="' + value + '"]', this.select).attr('selected', true); 
```

to:
```javascript
$('option[value="' + value + '"]', this.select).prop('selected', true);
```

**Comment by zellerda** [comment]
Corrected with issue #54, please try with the last master version

**Comment by kevas** [comment]
I trying new version 2.5 in a firefox browser. Displays only the first item.

Look at the screenshot:

![screen](https://cloud.githubusercontent.com/assets/227353/9193846/f167d264-4016-11e5-8a02-f1e50a49d9f1.png)

**Comment by zellerda** [comment]
Your select element MUST have multiple attribute before tokenize initialization
https://github.com/zellerda/Tokenize/issues/20

**Comment by kevas** [comment]
So, I have in select element add multiple attribute. Init js script is below select element.
I get this error in console: 
```
TypeError: this.tokensContainer.sortable is not a function
```

**Comment by zellerda** [comment]
![2015-08-11_11-21-47](https://cloud.githubusercontent.com/assets/140013/9194401/45775f88-401b-11e5-824e-deec436ea0a8.png)

**Comment by zellerda** [comment]
I will check that !

**Comment by kevas** [comment]
I have not option sortable.

This is my init script:

```javascript
$('.multiselectbox').tokenize({ displayDropdownOnFocus: true });
```

**Comment by zellerda** [comment]
Sorry I was to fast in my answer, that's corrected with the last version

**Comment by kevas** [comment]
Thank you for the quick action. It works perfectly.
