### ISSUE TITLE
How to refresh or trigger update after updating the underlying select

### ISSUE THREAD

**Issue by sabkaraja** [zellerda/Tokenize#60]
Let me explain this with a sample:

i have initialized the tokenize like this:
$('#service_list').tokenize({ maxElements:5,
		datas: '/myserver/ServiceTypesData/'
});

This works fine. However, using js, if I push or modify the underlying options, it doesnt update in tokenize. the following code doesnt work.

$('#service_list').empty().append($("<option></option>").attr("value",data.servicetype_id).text(data.servicetype));

Is there a way to push the new options into tokenize directly? something like $('#service_list').tokenize({options: [....]});

**Comment by zellerda** [comment]
You can use the api
```javascript
$('#my_tokenize').'tokenize().tokenAdd('value', 'text');
```

**Comment by sabkaraja** [comment]
Hi. it worked. The version I picked up from git was 2.4.3. Upgrading to the latest version worked.

However theres a new issue. Default options in select doesnt show up. I am facing these issues in JQM.

http://jsfiddle.net/ewsphc0u/

Sorry to reopen this issue

thanks.
