### ISSUE TITLE
displayDropdownOnFocus error

### ISSUE THREAD

**Issue by khaolek** [zellerda/Tokenize#62]
i use displayDropdownOnFocus = true and datas = json (data from url) is error on focus event on mouse focus textbox. The data from json can't display and i key someone data in textbox data from json display complete. i edit file jquery.tokenize.js on line 161 add else box can display complete.(sorry for bad english.)

**Comment by zellerda** [comment]
Hi, the options displayDropdownOnFocus works only with local datas (datas = 'select'), its because returned data with the search input empty may affect the performance of the plugin
