### ISSUE TITLE
improve handling for ajax errors

### ISSUE THREAD

**Issue by brettmc** [zellerda/Tokenize#64]
If an ajax/json request results in an error HTTP response code, the current behaviour is to log the error to console, but the end user just gets an empty select list.
It would be good to be able to display an error message to the end user in this situation.

I'm imagining a ```jsonErrorMessageField``` option, so that I can craft my error response to contain the message to be displayed...?

**Comment by brettmc** [comment]
...or something like this, which allows developer to handle their own errors?
```javascript
onAjaxError(function(XHR, textstatus){});
```

**Comment by brettmc** [comment]
@zellerda if you can give me some guidance as to which direction to take (or another), I'm happy to do the initial work and submit a pull request...

**Comment by zellerda** [comment]
Hi thanks for your proposition, I have implemented in the last commit, is it what you want ?

**Comment by brettmc** [comment]
That's perfect, love your work and your responsiveness!
