### ISSUE TITLE
call displaydropdownonfocus when click on button

### ISSUE THREAD

**Issue by nirmalrajs** [zellerda/Tokenize#71]
Hi,

i am using tokenize. i like it very much... but having not do some custom options.. any how i like to continue this tokenize....

    var location_tokenize = $('select#locations');

    location_tokenize.tokenize({  
        placeholder: "Type a locations name",
        newElements: false,
        maxElements: 5,
        onAddToken: function( value, txt, e ){
        },
        onRemoveToken: function() {
        },
        displayDropdownOnFocus: true
    });

     input type="submit" name="search_btn" id="search_btn" 

     $("#search_btn").on('click', function(e) {
         e.preventDefault();
         //  call displayDropdownOnFocus
     });

how can do i? please help me to fix this issue...

**Comment by zellerda** [comment]
Hi you can try
```javascript
$("#search_btn").on('click', function(e) {
     e.preventDefault();
     $('.TokensContainer').trigger('click');
});
