### ISSUE TITLE
How to disable option?

### ISSUE THREAD

**Issue by ivanjaros** [zellerda/Tokenize#72]
Hi,
I have one option that I want to hide/make unselectable. Does this plugin allow that? I haven't seen any method for it.

**Comment by zellerda** [comment]
https://www.zellerda.com/projects/jquery/tokenize
Section "Using the api" you can find "enable" and "disable" method

**Comment by ivanjaros** [comment]
a) it does not have documentation in the API section, just in how to use section
b) that, from my understanding, disables the whole element, I just want to hide/disable a single option

**Comment by zellerda** [comment]
Ok I understand, just access directly to the option in the select with jquery and disable it.

**Comment by ivanjaros** [comment]
Neither prop('disabled', true) or attr('disabled', 'disabled') is working.

**Comment by zellerda** [comment]
If you use AJAX that will not work, you have to filter your items on the server side

Here is my sample test:

```html
<select class="tokenize select" multiple="multiple">
    <option selected value="Adrienne">Adrienne</option>
    <option selected value="Nevada">Nevada</option>
    <option value="Petra">Petra</option>
    <option value="Georgia">Georgia</option>
    <option value="Ashley">Ashley</option>
    <option value="Silvia">Silvia</option>
</select>
<script>
    $('.tokenize').tokenize({});
    $('.tokenize option[value=Petra]').prop('disabled', true);
</script>
```

**Comment by ivanjaros** [comment]
I am not using ajax.

My script is:
```
(function($) {

  // DOM ready.
  $(function() {

    // Initialize tokenize script on all select elements with multiple
    // choices.
    // Allow elements to opt-out by using the 'skip-tokenize' class.
    $('select[multiple="multiple"]').once('tokenize').not('.skip-tokenize').each(function() {
      $(this).find('option[value="_none"]').prop('disabled', true);
      // Allow elements to provide placeholder.
      var placeholder = $(this).data('tokenize-placeholder') || false;
      // Allow elements to use custom configuration via 'data-tokenize-config' attribute.
      var default_config = { displayDropdownOnFocus: true, 'placeholder': placeholder };
      var config = $(this).data('tokenize-config') || default_config;
      $(this).tokenize(config);
    });

  });

})(jQuery);
```

My html is:
```
<select class="form-select" id="edit-tags" name="tags[]" multiple="multiple" aria-describedby="edit-tags--description" data-drupal-selector="edit-tags"><option selected="selected" value="_none">- None -</option><option value="33">Test</option></select>
```

**Comment by zellerda** [comment]
Found, just correct like this
```
$(this).find('option[value="_none"]').prop('disabled', true).prop('selected', false);
```
If an element is already selected you cannot disable it

**Comment by ivanjaros** [comment]
Thanks, but that just un-made it default value. The option can still be selected - it is present in the list. I do not think disable works in this case at all. Maybe removing the option completely would be a better option?

**Comment by zellerda** [comment]
Yes removing the option will be the best solution.

**Comment by ivanjaros** [comment]
Ok, thanks.

**Comment by mcory** [comment]
At some point in 2015 the .disable() method was added to the jquery.tokenize library.
You call disable all options like this:
$('#idOfMySelect').data('tokenize').disable();
