### ISSUE TITLE
Multiple values on initialize when using JSON

### ISSUE THREAD

**Issue by henninghorn** [zellerda/Tokenize#75]
Hi David

Awesome library!

I'm using Tokenize to suggest tags, so far so good.

I'm using this config when initializing:
````javascript
var tags = $('#tag_suggest');
tags.tokenize({
   datas: 'MY_URL',
   dataType: 'json',
   searchParam: 'search',
   newElements: false,
   debounce: 250,
   autosize: true,
   placeholder: 'Placeholder text',
   valueField: 'id',
   textField: 'tag',
   sortable: true
});
````
The above works great, I get suggestions and I'm not able to create tags that doesn't exists.

But I would like to be able to display the tags currently added to an article - when you're editing an existing article, so I thought I just needed to add them in the select box like this:
````html
<select name="tags" id="tag_suggest">
  <option value="123">My tag</option>
  <option value="321">Another tag</option>
</select>
````

The above will only display the "My tag" in the select box, not both of the tags. In other words, only the first tag - I tried adding more than two tags.
To this seems like a bug.

I got around this by doing this:
````javascript
// Can't add new elements without changing this
tags.tokenize().options.newElements = true;

// Loop tags and adding them manually like this:
tags.tokenize().tokenAdd(ID, TAG_NAME);

// Disable adding unknown tags
tags.tokenize().options.newElements = false;
````

I also tried running tags.tokenize().remap() - that didn't work either.

Just wanted to let you know about this.

**Comment by zellerda** [comment]
I you missed the selected attribute:
```html
<select name="tags" id="tag_suggest">
  <option value="123" selected="selected">My tag</option>
  <option value="321" selected="selected">Another tag</option>
</select>
```

**Comment by henninghorn** [comment]
This still results in only one tag being displayed.
But this time it's only the last one that's being displayed.

**Comment by zellerda** [comment]
Sorry add multiple attribute to your select

**Comment by henninghorn** [comment]
Ah, that worked - thank you for your quick response.
Makes sense that the markup should be like that.
