### ISSUE TITLE
Bower.json and bower.io version update to 2.6

### ISSUE THREAD

**Issue by billvieux** [zellerda/Tokenize#79]
Looks like bower is not yet updated for 2.6

**Comment by zellerda** [comment]
Hi the version 2.6 has not been relased at this time, the last version is 2.5.2

**Comment by billvieux** [comment]
of course. thank you for your blazing fast responses and enhancements! is there a target timeframe for 2.6 to be released?

**Comment by zellerda** [comment]
Probably one week but I'm not sure from now, after that I will create a new tokenize version (3.0) with bootstrap support, event based, etc...
