### ISSUE TITLE
Pasting in existing tokens and new tokens with a comma results in commas in the token

### ISSUE THREAD

**Issue by billvieux** [zellerda/Tokenize#83]
When pasting in a string like 'a,b' into a field with tokens 'a' and 'b', the search input contains 'a,b' (includes the comma). I expected the search input be empty.

**Comment by zellerda** [comment]
You cannot get the input empty when a character is not allowed, but you can change the "delimiter" option

**Comment by billvieux** [comment]
The behavior is a little odd because it will work as expected if the existing token is only 'a'. In that case, 'b' is correctly added. The only scenario that is unexpected is when all the tokens in the string are already present.
