### ISSUE TITLE
Tokenizer faces Problems when put into resizable div

### ISSUE THREAD

**Issue by mandar-k** [zellerda/Tokenize#85]

**Comment by zellerda** [comment]
Please provide more explications !

**Comment by mandar-k** [comment]
I was using tokenizer to create tags like gmail composer,you can  have a look at how the To line on gmail works while an email is being created. Once the user goes to the body of the email, the To recipients appear simpler.
and that too into a re sizable container. Didn't find much use.

**Comment by zellerda** [comment]
You have just to add css to .Tokenize div using like "width: 100%"
