### ISSUE TITLE
Ajax request needs to be POST instead of GET (fix provided, please apply)

### ISSUE THREAD

**Issue by ethaniel** [zellerda/Tokenize#86]
Right now, tokenizer sends it ajax requests through GET.
If I use a search value with a hashtag, like #example - it doesn't go through (the GET request is passed without the search value):

![image](https://cloud.githubusercontent.com/assets/941973/11303634/f07cf2ba-8fb4-11e5-807b-a4d11f72cd09.png)

I tried using escape() to protect the value, but it fucks up non-US characters (russian for example) and I need to decode them server-side.
![image](https://cloud.githubusercontent.com/assets/941973/11303668/14cce72e-8fb5-11e5-8926-8c9c0ec04dba.png)

The only way to get this fixed all together is to send the ajax request through POST:
![image](https://cloud.githubusercontent.com/assets/941973/11303564/9c48faa4-8fb4-11e5-9834-3f398151f0c3.png)

![image](https://cloud.githubusercontent.com/assets/941973/11303701/4348ac46-8fb5-11e5-9603-0e7ef3f1aeff.png)

**Comment by zellerda** [comment]
Please try the last release, the bug with non-US characters have been resolved with issue #80
