### ISSUE TITLE
Change JSON URL

### ISSUE THREAD

**Issue by notRuslan** [zellerda/Tokenize#87]
Impossible change "datas" url.
For example I have Country select and tokenized Cities select.
Will be better to change url 
/json.php?country_id=29   - for one counry
and if user selected anther country
/json.php?country_id=58

please, add this functionality.

**Comment by zellerda** [comment]
You can try
```javascript
$('#country_select').on('change', function(){
    $('#tokenize').tokenize().options.datas = '/json.php?country_id=' + $(this).val();
})
```

**Comment by notRuslan** [comment]
It's works fine thank you!

**Comment by notRuslan** [comment]
Thank you very much!

BR.Ruslan.
 


    On Monday, November 23, 2015 8:42 AM, David Zeller <notifications@github.com> wrote:
 

 You can try$('#country_select').on('change', function(){
    $('#tokenize').tokenize().options.datas = '/json.php?country_id=' + $(this).val();
})—
