### ISSUE TITLE
<options> with the same value are not displayed

### ISSUE THREAD

**Issue by ZaneCEO** [zellerda/Tokenize#88]
Loving yor plugin so far, thank you for developing it!

Just a minor annoiance: I found out that if the select has multiple option with the same value the dropdown will display only once

````
<select>
    <option value="1">Try and add me: the dropdown will display</option>
    <option value="1">I will never be shown because I've the same value as the one before</option>
</select>
````

**Comment by zellerda** [comment]
Currently tokenize dosen't support same options value, I have also to check with W3C if it possible

**Comment by ZaneCEO** [comment]
Works just fine with a standard <select multiple>, doesn't it?
