### ISSUE TITLE
Need to close opening dropdown when focus the other token

### ISSUE THREAD

**Issue by hungpvdev** [zellerda/Tokenize#94]
![dropdownbug](https://cloud.githubusercontent.com/assets/7043979/11586647/2c1848d6-9aa7-11e5-9669-60d76bfa97c9.PNG)

Multiple instance of tokenize & displayDropdownOnFocus = true.
Need to close all other opening dropdown before show the new one.

**Comment by kelo95** [comment]
This is my solution. Hope this can help you.


this.tokensContainer.on('click', function (e) {
                e.stopImmediatePropagation();
                var Dropdown = $this.container.find(".Dropdown");
                if (Dropdown.css("display") == "none") {
                    $this.container.parent().find(".caret").addClass("open");
                    Dropdown.css("display", "block");

                    $this.searchInput.get(0).focus();

                    $this.updatePlaceholder();

                    $this.search();
                } else {
                    $this.container.parent().find(".caret").removeClass("open");
                    Dropdown.css("display", "none");
                }
            });

            this.searchInput.on('blur', function () {
                setTimeout(function () { 
                    var Dropdown = $this.container.find(".Dropdown");
                    $this.container.parent().find(".caret").removeClass("open");
                    Dropdown.css("display", "none");
                }, 200);
                $this.tokensContainer.removeClass('Focused');
                $this.container.removeClass('token-control-Focused');
            });

            $(window).on('click', function(){
                $this.dropdownHide();
            });
