### ISSUE TITLE
beforeDelete

### ISSUE THREAD

**Issue by webbluffer** [zellerda/Tokenize#99]
i m using Tokenizem, this is very helpful, i am facing an issue is, i want to confirm before delete.
the option onRemoveToken works when Token has been removed not before remove.
is there anyway to give alert to user before deleting the Token?
.
other way 
onRemoveToken  returns value and object, could i find my text from this object, if this is possible then i can add Token back using $('#tokenize').tokenize().tokenAdd(value, text);

waiting.....

**Comment by zellerda** [comment]
Won't fix for this version, for the next version it will be event based
